name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build_DataStructures with dotnet
      run: dotnet build ${workspaceFolder}/DataStructures

    - name: Run_Tests with dotnet
      run: dotnet test ${workspaceFolder}/Tests
